# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Exemplar-based prediction computation
#' 
#' @param values numeric vector with experienced values
#' @param features numeric matrix with feature values
#' @param w numeric vector of weights (model parameter)
#' @param r square root in distance metic (model parameter)
#' @param q exponent in distance metric (model parameter)
#' @param lambda sensitivity (model parameter)
#' @param b bias parameter vector for classification (model parameter), must be NA for judgments
#' @param lastLearnTrial integer last trial of learning phase
#' @param firstOutTrial integer first trial of output, starting the predictions later
#' @examples
#' # none
#' @export
ebm_cpp <- function(values, features, w, r, q, lambda, b, lastLearnTrial, firstOutTrial) {
    .Call(`_cogscimodels_ebm_cpp`, values, features, w, r, q, lambda, b, lastLearnTrial, firstOutTrial)
}

lexicographic <- function(I) {
    .Call(`_cogscimodels_lexicographic`, I)
}

indicators <- function(features, splitcriteria) {
    .Call(`_cogscimodels_indicators`, features, splitcriteria)
}

