# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Exemplar-based prediction computation
#' 
#' @param criterion numeric vector with experienced criterion
#' @param features numeric matrix with feature criterion
#' @param w numeric vector of weights (model parameter)
#' @param r square root in distance metic (model parameter)
#' @param q exponent in distance metric (model parameter)
#' @param lambda sensitivity (model parameter)
#' @param b bias parameter vector for classification (model parameter), must be NA for judgments
#' @param fw weight vector with a weight for each feature combination
#' @param lastLearnTrial integer last trial of learning phase
#' @param firstOutTrial integer first trial of output, starting the predictions later
#' @examples
#' # none
#' @export
NULL

ebm_cpp <- function(criterion, features, w, r, q, lambda, b, wf, lastLearnTrial, firstOutTrial) {
    .Call(`_cogscimodels_ebm_cpp`, criterion, features, w, r, q, lambda, b, wf, lastLearnTrial, firstOutTrial)
}

lexicographic <- function(I) {
    .Call(`_cogscimodels_lexicographic`, I)
}

indicators <- function(features, splitcriteria) {
    .Call(`_cogscimodels_indicators`, features, splitcriteria)
}

#' Exemplar-based prediction computation
#' 
#' @param x numeric matrix with outcomes
#' @param p numeric matrix with probabilities
#' @param w numeric vector with aspiration leel
#' @param beta parameter
#' @param delta parameter
#' '
#' @export
shortfall_cpp <- function(x, p, a, beta, delta) {
    .Call(`_cogscimodels_shortfall_cpp`, x, p, a, beta, delta)
}

